version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '3000:3000'
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - '4000:4000'
    environment:
      - CONNECTION_STRING=mongodb://mongo:27017/mydatabase
      - PORT=4000
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: